const pages = {
  home: {
    heading: "SparkleBot",
    tagline: "Think Before You Click",
    description:
      "An AI-powered anti-scam portal that helps users check suspicious text, URLs, screenshots, and get practical scam guidance from SparkleBot."
  },
  checker: {
    heading: "Scam Detector",
    description:
      "Paste suspicious text, check a URL, or upload a screenshot. Gemini extracts text from images, then OpenAI reviews the content for scam risk, red flags, and safer next steps."
  },
  chatbot: {
    heading: "AI Chatbot",
    description:
      "Ask SparkleBot about suspicious messages, scam warning signs, and safer next steps."
  },
  report: {
    heading: "Report Scam",
    description:
      "Submit suspicious activity for admin review through the connected n8n workflow."
  },
  scamTrends: {
    heading: "Scam Trends Dashboard",
    description:
      "Review processed scam trend summaries generated by n8n from Google Sheets."
  },
  feedback: {
    heading: "Feedback",
    description:
      "Share whether SparkleBot was helpful and what should be improved."
  },
  about: {
    heading: "About AI",
    description:
      "SparkleBot combines practical web tools with modern AI concepts for scam education and safer decision-making."
  }
};

const chatbotQuestions = [
  "Is this message asking for my bank details a scam?",
  "What should I do if I clicked a suspicious link?",
  "How do I recognize a job scam?",
  "Can you explain phishing in simple terms?"
];

exports.getPage = (key) => pages[key];
exports.getChatbotQuestions = () => chatbotQuestions;
