const pages = {
  home: {
    heading: "SparkleBot",
    tagline: "Think Before You Click",
    description:
      "An AI-powered anti-scam portal that helps users check suspicious text, URLs, screenshots, and get practical scam guidance from SparkleBot."
  },
  checker: {
    heading: "Scam Detector",
    description:
      "Paste suspicious text, check a URL, or upload a screenshot. The n8n workflow extracts image text, reviews the content for scam risk, and returns red flags with safer next steps."
  },
  chatbot: {
    heading: "AI Chatbot",
    description:
      "Ask SparkleBot about suspicious messages, scam warning signs, and safer next steps."
  },
  report: {
    heading: "Report Scam",
    description:
      "Submit suspicious activity for admin review through the connected n8n workflow."
  },
  scamTrends: {
    heading: "Scam Trends Dashboard",
    description:
      "Review processed scam trend summaries generated by n8n from Google Sheets."
  },
  feedback: {
    heading: "Feedback",
    description:
      "Share whether SparkleBot was helpful and what should be improved."
  },
  about: {
    heading: "About AI",
    description:
      "SparkleBot combines practical web tools with modern AI concepts for scam education and safer decision-making."
  }
};

const defaultLearningPrompts = [
  "What warning signs should I learn from this result?",
  "What should I do before replying or clicking anything?",
  "How can I verify if this message is legitimate?",
  "What steps should I take if I already shared information?"
];

const learningPromptsByScamType = {
  phishing: [
    "How do phishing scams try to steal passwords or bank details?",
    "What signs show that a link or login page may be fake?",
    "What should I do if I clicked a phishing link?",
    "How can I verify a message claiming to be from a bank or government service?"
  ],
  job: [
    "What are common warning signs of fake job offers?",
    "Why do scammers ask for payment before hiring?",
    "How can I verify that a recruiter or company is real?",
    "What should I do if I already sent my personal details?"
  ],
  payment: [
    "How do payment scams pressure people into transferring money?",
    "What checks should I do before paying someone online?",
    "What should I do if I already made a payment?",
    "How can I spot fake invoices or refund requests?"
  ],
  impersonation: [
    "How do impersonation scams pretend to be trusted people or services?",
    "What should I check before trusting an urgent request?",
    "How can I verify an official message safely?",
    "What should I do if I shared information with an impersonator?"
  ],
  investment: [
    "What warning signs appear in investment scams?",
    "Why are guaranteed returns a red flag?",
    "How can I verify an investment platform?",
    "What should I do if I already transferred money?"
  ]
};

function getChatbotQuestions(scamType = "") {
  const normalizedScamType = String(scamType).trim().toLowerCase();
  const matchedType = Object.keys(learningPromptsByScamType).find((type) =>
    normalizedScamType.includes(type)
  );

  if (matchedType) {
    return learningPromptsByScamType[matchedType];
  }

  return defaultLearningPrompts;
}

exports.getPage = (key) => pages[key];
exports.getChatbotQuestions = getChatbotQuestions;
